//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCInsight.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class admin_csmariseEntities : DbContext
    {
        public admin_csmariseEntities()
            : base("name=admin_csmariseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClockInRequest> ClockInRequest { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryRequest> InventoryRequest { get; set; }
        public virtual DbSet<InventorySitewise> InventorySitewise { get; set; }
        public virtual DbSet<InventoryTransaction> InventoryTransaction { get; set; }
        public virtual DbSet<LeaveRequest> LeaveRequest { get; set; }
        public virtual DbSet<SiteUser> SiteUser { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskDepartment> TaskDepartment { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserDepartment> UserDepartment { get; set; }
        public virtual DbSet<AdvancePaymentRequest> AdvancePaymentRequest { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<DailyTaskStatus> DailyTaskStatus { get; set; }
    }
}
